spring:
  datasource:
    url: jdbc:postgresql://10.0.0.1:5432/fbank
    username: omar
    password: omar
    driver-class-name: org.postgresql.Driver
  data:
    web:
      pageable:
        max-page-size: 25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
jwt:
  secret: ${JWT_SECRET}