spring:
  datasource:
    url: jdbc:postgresql://10.0.0.1:5432/fbank
    username: omar
    password: omar
#    sql:
#      init:
#        mode: always
  jpa:
    #generate-ddl: false
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never