spring:
  datasource:
    url: jdbc:postgresql://10.0.0.1:5432/fbank
    username: omar
    password: omar
  data:
    web:
      pageable:
        max-page-size: 25
  #    sql:
  #      init:
  #        mode: always
  jpa:
    #generate-ddl: false
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never